#multistage with reinstalling
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY app.js .
RUN npm run build

FROM node:18-alpine
WORKDIR /app
#copies package.json 
COPY --from=builder /app/package*.json ./  
#installs the required package       
RUN npm install --omit=dev
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/app.js"]
